...
fn main() {
    ...
    let thread_1 = thread::spawn(move || {
        println!("Thread 1: I am doing some work");
        println!("Thread 1: I am doing some more work");
        thread::sleep(Duration::from_secs(2)); // added
        println!("Thread 1: Printing the updated data");
        ...
    });
    ...
}